#!/usr/bin/env bash
# Configure server with: HAproxy version 1.5 or greater
# Distributes request using roundrobin; sends traffic to servers: web-01 and web-02

CFG="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 256398-web-01 54.210.173.28 check\n\tserver 256398-web-02 54.144.141.106 check\n"

sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8\*

# Make sure HAproxy can be managed via an init script
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure to include roundrobin and two servers
sudo sed -i "\$a $CFG" /etc/haproxy/haproxy.cfg

sudo service haproxy start