#!/usr/bin/env bash
# Installs HAProxy version 2.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install -y haproxy=2.8.\*

sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen alx 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 256398-web-01 54.210.173.28:80 check
    server 256398-web-02 54.144.141.106:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start