#!/usr/bin/env bash
# Infinite loop creates file with pid, catches signal, and removes file/exits:
# Ctrl-C (SIGINT), kill (SIGTERM), and ctrl-| (SIGQUIT)

rm_file()
{
        rm -f /var/run/myscript.pid
	exit
}
trap "echo 'Y U no love me?'!" SIGINT
trap "echo 'I hate the kill command'; rm_file" SIGTERM
trap "echo 'I hate the kill command'; rm_file"  SIGQUIT

echo $$ >> /var/run/myscript.pid

while true
do
        echo "To infinity and beyond"
        sleep 2
done
